In [1]:
import math

import numpy as np
import scipy
import torch
from sentence_transformers import SentenceTransformer

In [2]:
documents = [
    'Bugs introduced by the intern had to be squashed by the lead developer.',
    'Bugs found by the quality assurance engineer were difficult to debug.',
    'Bugs are common throughout the warm summer months, according to the entomologist.',
    'Bugs, in particular spiders, are extensively studied by arachnologists.'
]

In [3]:
# Load pre-trained model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

In [4]:
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [5]:
#Generate model embeddings
embeddings = model.encode(documents)

In [22]:
embeddings

array([[-0.22804396, -0.24647696, -0.00319299, ...,  0.45528114,
         0.63419724,  0.5375052 ],
       [-0.3579157 , -0.32083997,  0.15963268, ..., -0.07050659,
         0.92750233,  0.3437731 ],
       [ 0.20302913, -0.26898587,  0.16285129, ..., -0.19650973,
        -0.03379872,  0.5956154 ],
       [-0.0426428 , -0.4572159 , -0.09526511, ..., -0.58030707,
         0.17248403,  0.09127871]], shape=(4, 384), dtype=float32)

Manual implementation of L2 distance calculation

In [18]:
def euclidean_distance_fn(vector1, vector2):
    squared_sum = sum((x - y) ** 2 for x, y in zip(vector1, vector2))
    return math.sqrt(squared_sum)

In [19]:
euclidean_distance_fn(embeddings[0], embeddings[1])

5.9617892115561535

In [ ]:
#this calculated the distance but in effcient way
l2_distace_manual = np.zeros([4,4])
for i in range(embeddings.shape[0]):
    for j in range(embeddings.shape[0]):
        
        l2_distace_manual[i][j] = euclidean_distance_fn(embeddings[i],embeddings[j])

l2_distace_manual

array([[0.        , 5.96178921, 7.33939885, 7.15578249],
       [5.96178921, 0.        , 7.76861453, 7.39358971],
       [7.33939885, 7.76861453, 0.        , 5.91992767],
       [7.15578249, 7.39358971, 5.91992767, 0.        ]])

In [ ]:
#Efficient way
#this calculated the distance but in effcient way
l2_distace_manual = np.zeros([4,4])
for i in range(embeddings.shape[0]):
    for j in range(embeddings.shape[0]):
        if i<j:
            l2_distace_manual[i,j] = euclidean_distance_fn(embeddings[i],embeddings[j])
        elif i>j:
            l2_distace_manual[i,j] = 

l2_distace_manual


array([[0.        , 5.96178921, 7.33939885, 7.15578249],
       [0.        , 0.        , 7.76861453, 7.39358971],
       [0.        , 0.        , 0.        , 5.91992767],
       [0.        , 0.        , 0.        , 0.        ]])